### ISSUE TITLE
[Request] Add OLED Keyboard

### ISSUE THREAD

**Issue by iAmANoobProgrammer** [dayanch96/YTLite#201]
### Describe the feature request

```yaml
I really like the OLED theme however it would be nice if the keyboard were also OLED, and the theme would be complete.

Using YouTube Plus tweaked version.

YouTube Plus version: 5.0.2

YouTube version: 19.39.1
```

### Post Requisites

- [X] I have checked that a similar feature request has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [x] Provided a detailed description of the request and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this request, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the request being closed without discussion, and repeated violations may lead to restrict account from further participation.**
