### ISSUE TITLE
[Bug] App Crashes when I tap on Share

### ISSUE THREAD

**Issue by shahin365** [dayanch96/YTLite#202]
### Describe the bug

```yaml
The app crashes every time I tap on Share. I tried it with regular videos, short videos, both playing and paused, and the result is always the same: the app crashes instantly after I tap on the Share button.

Youtube version: 19.36.1
YTPlus version: 5.0.2
iOS: 18.0 (22A3354)
iPhone: iPhone 12 Pro Max
```

### Steps to reproduce

```yaml
1. Open app
2. Play any video
3. tap on Share button
```

### Crashlog

[YouTube-2024-10-03-160735.ips.zip](https://github.com/user-attachments/files/17249969/YouTube-2024-10-03-160735.ips.zip)

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**
