### ISSUE TITLE
App crashes when click on Download Video or Download audio

### ISSUE THREAD

**Issue by eduedp** [dayanch96/YTLite#229]
### Describe the bug

```yaml
The app crashes every time I tap on Download Video ou Download audio. I tried it with regular videos, short videos, both playing and paused, and the result is always the same.

Youtube version: 19.44.4
YTPlus version: 5.0.2
iOS: 16.3.1
iPhone: iPhone 13 Pro Max
```

### Steps to reproduce

```yaml
1. Play any video
2. Click on Download
3. Click on Download video or Download audio
4. App crashes
```

### Crashlog

[YouTube-2024-11-05-130048.zip](https://github.com/user-attachments/files/17636287/YouTube-2024-11-05-130048.zip)

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**
