### ISSUE TITLE
Option to Remove "Play next in queue" doesn't work

### ISSUE THREAD

**Issue by eduedp** [dayanch96/YTLite#230]
### Describe the bug

```yaml
The option Remove "Play next in queue" in `Settings -> YouTube Plus -> Interface -> Context menu` doesn't remove the option from menu. All the other remove options are working.

Youtube version: 19.44.4
YTPlus version: 5.0.2
iOS: 16.3.1
iPhone: iPhone 13 Pro Max
```

### Steps to reproduce

```yaml
1. Enable Remove "Play next in queue" inside `Settings -> YouTube Plus -> Interface -> Context menu`
2. Tap and hold on a video thumbnail or click the three dots to bring the context menu
3. See that "Play next in queue" is still showing
```

### Post Requisites

- [X] I have checked that a similar issue has not been reported before.
- [X] Verified the relevance of the project and the version you are using.
- [X] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [X] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**
