### ISSUE TITLE
Option to Remove "Play next in queue" stopped working again

### ISSUE THREAD

**Issue by eduedp** [dayanch96/YTLite#392]
### Describe the bug

```yaml
The option Remove "Play next in queue" in `Settings -> YouTube Plus -> Interface -> Context menu` is not removing the option from menu anymore. It was working until last week.

It's the same issue as #230 that was fixed on 5.1

Youtube version: 20.10.4 and 20.05.4
YTPlus version: 5.2b1 and 5.1
iOS: 18.2.1
iPhone: iPhone 13 Pro Max
```

### Steps to reproduce

```yaml
1. Enable Remove "Play next in queue" inside `Settings -> YouTube Plus -> Interface -> Context menu`
2. Tap and hold on a video thumbnail or click the three dots to bring the context menu
3. See that "Play next in queue" is still showing
```

### Post Requisites

- [x] I have checked that a similar issue has not been reported before.
- [x] Verified the relevance of the project and the version you are using.
- [x] Provided a detailed description of the problem and have filled in all required fields.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.
- [x] By submitting this issue, **I confirm that I have filled in all the necessary fields and complied with the guidelines. Failure to comply may result in the issue being closed without discussion, and repeated violations may lead to restrict account from further participation.**
